<h1>Ejercicio NumPY</h1>

In [ ]:
import numpy as np

In [ ]:
edades = np.random.uniform(
    size=(3,3),
    low=20,
    high=50
    ).round()
edades

array([[48., 20., 27.],
       [28., 27., 39.],
       [33., 30., 48.]])

In [ ]:
ingresos = np.random.uniform(
    size=(3,3),
    low=2,
    high=5
    ).round(decimals=9)*1e6
ingresos

array([[2589360.68 , 2148875.241, 2103573.119],
       [3198563.716, 2609296.171, 3562046.25 ],
       [2172924.418, 4839919.881, 3188620.641]])

In [ ]:
union = np.stack([edades,ingresos], axis=2).reshape(9,2)
union

array([[4.80000000e+01, 2.58936068e+06],
       [2.00000000e+01, 2.14887524e+06],
       [2.70000000e+01, 2.10357312e+06],
       [2.80000000e+01, 3.19856372e+06],
       [2.70000000e+01, 2.60929617e+06],
       [3.90000000e+01, 3.56204625e+06],
       [3.30000000e+01, 2.17292442e+06],
       [3.00000000e+01, 4.83991988e+06],
       [4.80000000e+01, 3.18862064e+06]])

In [ ]:
mayor_que = union >= [20,2e6]
menor_que = union <= [30,5e6]
filtro = np.logical_and(mayor_que,menor_que)
filtro


array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [ True,  True],
       [False,  True]])

In [ ]:
filtro_def = np.logical_and.reduce(filtro,1)
filtro_def

array([False,  True,  True,  True,  True, False, False,  True, False])

In [ ]:
res = union[filtro_def]
res 


array([[2.00000000e+01, 2.14887524e+06],
       [2.70000000e+01, 2.10357312e+06],
       [2.80000000e+01, 3.19856372e+06],
       [2.70000000e+01, 2.60929617e+06],
       [3.00000000e+01, 4.83991988e+06]])