<h1>Ejercicio NumPY</h1>

In [ ]:
import numpy as np

In [ ]:
edades = np.random.uniform(
    size=(3,3),
    low=20,
    high=50
    ).round()
edades

array([[48., 20., 27.],
       [28., 27., 39.],
       [33., 30., 48.]])

In [85]:
ingresos = np.random.uniform(
    size=(3,3),
    low=2,
    high=5
    ).round(decimals=9)*1e3
ingresos

array([[3271.752769, 4574.464808, 3049.994977],
       [2550.386939, 4933.442179, 4983.773592],
       [3619.999941, 4286.086744, 3792.791683]])

In [86]:
union = np.stack([edades,ingresos], axis=2).reshape(9,2)
union

array([[  48.      , 3271.752769],
       [  20.      , 4574.464808],
       [  27.      , 3049.994977],
       [  28.      , 2550.386939],
       [  27.      , 4933.442179],
       [  39.      , 4983.773592],
       [  33.      , 3619.999941],
       [  30.      , 4286.086744],
       [  48.      , 3792.791683]])

In [87]:
mayor_que = union >= [20,2e3]
menor_que = union <= [30,5e3]
filtro = np.logical_and(mayor_que,menor_que)
filtro


array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [ True,  True],
       [False,  True]])

In [88]:
filtro_def = np.logical_and.reduce(filtro,1)
filtro_def

array([False,  True,  True,  True,  True, False, False,  True, False])

In [89]:
res = union[filtro_def]
res 


array([[  20.      , 4574.464808],
       [  27.      , 3049.994977],
       [  28.      , 2550.386939],
       [  27.      , 4933.442179],
       [  30.      , 4286.086744]])