<h1>Ejercicio NumPY</h1>

In [ ]:
import numpy as np

In [90]:
edades = np.random.uniform(
    size=(3,3),
    low=20,
    high=50
    ).round()
edades

array([[41., 47., 44.],
       [46., 40., 21.],
       [28., 27., 21.]])

In [91]:
ingresos = np.random.uniform(
    size=(3,3),
    low=2,
    high=5
    ).round(decimals=3)*1e3
ingresos

array([[2908., 4724., 4829.],
       [2098., 2278., 3662.],
       [3359., 4260., 2586.]])

In [92]:
union = np.stack([edades,ingresos], axis=2).reshape(9,2)
union

array([[  41., 2908.],
       [  47., 4724.],
       [  44., 4829.],
       [  46., 2098.],
       [  40., 2278.],
       [  21., 3662.],
       [  28., 3359.],
       [  27., 4260.],
       [  21., 2586.]])

In [93]:
mayor_que = union >= [20,2e3]
menor_que = union <= [30,5e3]
filtro = np.logical_and(mayor_que,menor_que)
filtro


array([[False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [94]:
filtro_def = np.logical_and.reduce(filtro,1)
filtro_def

array([False, False, False, False, False,  True,  True,  True,  True])

In [95]:
res = union[filtro_def]
res 


array([[  21., 3662.],
       [  28., 3359.],
       [  27., 4260.],
       [  21., 2586.]])